use `monitor`;

DROP TABLE IF EXISTS `threshold`;
CREATE TABLE `threshold` (
  `TYPE` varchar(32) NOT NULL,
  `NORMAL` int(11) NOT NULL,
  `WARNING` int(11) NOT NULL,
  PRIMARY KEY (`TYPE`)
);

DROP TABLE IF EXISTS `unit_seq`;
CREATE TABLE `unit_seq` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `sensor`;
DROP TABLE IF EXISTS `unit`;
CREATE TABLE `unit` (
  `UNIT_ID` char(16) NOT NULL DEFAULT 'UT00000000000000',
  `UNIT_NAME` varchar(128) NOT NULL,
  `PARENT_ID` char(16) DEFAULT NULL,
  `REMARK` varchar(256) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `LEAF` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNIT_ID`),
  KEY `PARENT_ID_INX` (`PARENT_ID`),
  KEY `UNIT_NAME_IDX` (`UNIT_NAME`),
  KEY `ACTIVE_IDX` (`ACTIVE`),
  KEY `LEAF_IDX` (`LEAF`)
);

DROP TRIGGER IF EXISTS `unit_BEFORE_INSERT`;
DELIMITER $$
CREATE TRIGGER `unit_BEFORE_INSERT` BEFORE INSERT ON `unit` FOR EACH ROW
BEGIN
	INSERT INTO unit_seq VALUES (NULL);
    SET NEW.UNIT_ID = CONCAT('UT', LPAD(LAST_INSERT_ID(), 14, '0'));
END$$
DELIMITER ;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `USER_ID` char(6) NOT NULL,
  `USER_NAME` varchar(64) NOT NULL,
  `MAIL_ADDRESS` varchar(64) NOT NULL,
  `USER_ROLES` varchar(128) DEFAULT NULL,
  `USER_PASSWORD` varchar(64) NOT NULL,
  `PHONE_NUMBER` varchar(20) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `USERNAME` (`USER_NAME`),
  KEY `USERMAIL` (`MAIL_ADDRESS`)
);

DROP TABLE IF EXISTS `unit_manager`;
CREATE TABLE `unit_manager` (
  `UNIT_ID` char(16) NOT NULL,
  `USER_ID` char(6) NOT NULL,
  PRIMARY KEY (`UNIT_ID`,`USER_ID`),
  KEY `UNIT_ID_IDX` (`UNIT_ID`),
  KEY `MANAGER_ID_IDX` (`USER_ID`)
);

CREATE TABLE `sensor` (
  `SENSOR_ID` char(16) NOT NULL,
  `SENSOR_NAME` varchar(128) DEFAULT NULL,
  `UNIT_ID` char(16) NOT NULL,
  `SENSOR_REMARK` varchar(1024) DEFAULT NULL,
  `SENSOR_SN` varchar(128) DEFAULT NULL,
  `SENSOR_MODEL` varchar(64) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`SENSOR_ID`),
  KEY `SENSOR_UNIT_ID_idx` (`UNIT_ID`),
  CONSTRAINT `SENSOR_UNIT_ID` FOREIGN KEY (`UNIT_ID`) REFERENCES `unit` (`unit_id`)
);

INSERT INTO `unit` VALUES ('UT00000000000001','/',NULL,'系统根节点',1,0);